// Chem+ app: the chemical safety records behind the Safety module.
//
// This is a study and recall aid, not a substitute for a real safety data sheet: the supplier's
// own SDS for the bottle in hand is what governs, because classification varies with purity and
// concentration. The module says so on screen. The data here is the widely agreed GHS
// classification for the common laboratory grade of each substance.
//
// First aid and storage are not written per chemical; they come from the hazard profile, so two
// corrosives cannot end up with contradictory advice. Incompatibilities are tags rather than free
// text so they translate and stay consistent.

import type { PictogramId } from "./pictograms";

export type SafetyCategory = "acid" | "base" | "solvent" | "oxidiser" | "toxic" | "salt" | "reactive" | "biochem";

export type FirstAidProfile = "corrosive" | "toxic" | "solvent" | "irritant" | "low";

export type StorageProfile = "corrosive" | "flammable" | "oxidiser" | "toxic" | "reactive" | "ambient" | "cold";

export type Incompatibility =
  | "strongAcids"
  | "strongBases"
  | "oxidisers"
  | "reducers"
  | "water"
  | "metals"
  | "organics"
  | "halogens"
  | "heat"
  | "light"
  | "air"
  | "ammonia"
  | "cyanides";

export interface SafetyChemical {
  id: string;
  name: string;
  nameTr: string;
  formula: string;
  cas: string;
  /** Other names it is looked up by, in either language. */
  synonyms: string[];
  category: SafetyCategory;
  pictograms: PictogramId[];
  signal: "danger" | "warning" | "none";
  /** H-codes; the wording comes from statements.ts. */
  hazards: string[];
  /** P-codes; the wording comes from statements.ts. */
  precautions: string[];
  firstAid: FirstAidProfile;
  storage: StorageProfile;
  incompatible: Incompatibility[];
  /** The one thing worth knowing that the codes do not say. */
  note?: { tr: string; en: string };
}

export const CATEGORY_LABELS: Record<SafetyCategory, { tr: string; en: string }> = {
  acid: { tr: "Asitler", en: "Acids" },
  base: { tr: "Bazlar", en: "Bases" },
  solvent: { tr: "Çözücüler", en: "Solvents" },
  oxidiser: { tr: "Oksitleyiciler", en: "Oxidisers" },
  toxic: { tr: "Toksik maddeler", en: "Toxic substances" },
  salt: { tr: "Tuzlar ve katılar", en: "Salts and solids" },
  reactive: { tr: "Reaktif maddeler", en: "Reactive substances" },
  biochem: { tr: "Biyokimya", en: "Biochemistry" },
};

export const INCOMPATIBILITY_LABELS: Record<Incompatibility, { tr: string; en: string }> = {
  strongAcids: { tr: "Güçlü asitler", en: "Strong acids" },
  strongBases: { tr: "Güçlü bazlar", en: "Strong bases" },
  oxidisers: { tr: "Oksitleyiciler", en: "Oxidising agents" },
  reducers: { tr: "İndirgeyiciler", en: "Reducing agents" },
  water: { tr: "Su", en: "Water" },
  metals: { tr: "Metaller", en: "Metals" },
  organics: { tr: "Organik maddeler", en: "Organic materials" },
  halogens: { tr: "Halojenler", en: "Halogens" },
  heat: { tr: "Isı ve alev", en: "Heat and flame" },
  light: { tr: "Işık", en: "Light" },
  air: { tr: "Hava ve nem", en: "Air and moisture" },
  ammonia: { tr: "Amonyak ve aminler", en: "Ammonia and amines" },
  cyanides: { tr: "Siyanürler", en: "Cyanides" },
};

export const FIRST_AID: Record<FirstAidProfile, { eyes: { tr: string; en: string }; skin: { tr: string; en: string }; inhaled: { tr: string; en: string }; swallowed: { tr: string; en: string } }> = {
  corrosive: {
    eyes: {
      tr: "En az 15 dakika göz duşunda, göz kapaklarını açık tutarak yıkayın. Hemen tıbbi yardım alın.",
      en: "Rinse at an eyewash station for at least 15 minutes, holding the eyelids open. Get medical help immediately.",
    },
    skin: {
      tr: "Kirlenmiş giysiyi hemen çıkarın, bölgeyi en az 15 dakika bol suyla yıkayın. Nötralize etmeye çalışmayın.",
      en: "Remove contaminated clothing at once and wash the area with plenty of water for at least 15 minutes. Do not try to neutralise.",
    },
    inhaled: {
      tr: "Temiz havaya çıkarın, rahat nefes alacak pozisyonda tutun. Solunum zorluğu varsa tıbbi yardım alın.",
      en: "Move to fresh air and keep in a position comfortable for breathing. Get medical help if breathing is difficult.",
    },
    swallowed: {
      tr: "Kusturmayın. Bilinci yerindeyse ağzı çalkalatın, su içirin. Hemen tıbbi yardım alın.",
      en: "Do not induce vomiting. If conscious, rinse the mouth and give water. Get medical help immediately.",
    },
  },
  toxic: {
    eyes: {
      tr: "En az 15 dakika bol suyla yıkayın. Hemen tıbbi yardım alın.",
      en: "Rinse with plenty of water for at least 15 minutes. Get medical help immediately.",
    },
    skin: {
      tr: "Kirlenmiş giysiyi çıkarın, bol su ve sabunla yıkayın. Hemen tıbbi yardım alın; maruz kalan kişiyi yalnız bırakmayın.",
      en: "Remove contaminated clothing and wash with plenty of soap and water. Get medical help immediately; do not leave the person alone.",
    },
    inhaled: {
      tr: "Kurtarıcı kendi güvenliğini almadan alana girmemelidir. Kişiyi temiz havaya çıkarın ve hemen 112'yi arayın.",
      en: "Rescuers must protect themselves before entering. Move the person to fresh air and call emergency services immediately.",
    },
    swallowed: {
      tr: "Kusturmayın. Bilinçsiz kişiye ağızdan bir şey vermeyin. Hemen zehir danışma merkezini (Türkiye: 114) arayın.",
      en: "Do not induce vomiting. Give nothing by mouth to an unconscious person. Call a poison centre immediately.",
    },
  },
  solvent: {
    eyes: {
      tr: "Göz kapaklarını açık tutarak en az 10 dakika yıkayın. Tahriş sürerse tıbbi yardım alın.",
      en: "Rinse for at least 10 minutes holding the eyelids open. Get medical help if irritation persists.",
    },
    skin: {
      tr: "Kirlenmiş giysiyi çıkarın, bol su ve sabunla yıkayın. Tahriş sürerse tıbbi yardım alın.",
      en: "Remove contaminated clothing and wash with soap and water. Get medical help if irritation persists.",
    },
    inhaled: {
      tr: "Temiz havaya çıkarın. Baş dönmesi veya uyuşukluk varsa tıbbi yardım alın.",
      en: "Move to fresh air. Get medical help if dizziness or drowsiness occurs.",
    },
    swallowed: {
      tr: "Kusturmayın — akciğere kaçması ciğer hasarı yapar. Ağzı çalkalatın ve tıbbi yardım alın.",
      en: "Do not induce vomiting - aspiration into the lungs causes damage. Rinse the mouth and get medical help.",
    },
  },
  irritant: {
    eyes: {
      tr: "Birkaç dakika bol suyla yıkayın. Tahriş sürerse tıbbi yardım alın.",
      en: "Rinse with plenty of water for several minutes. Get medical help if irritation persists.",
    },
    skin: { tr: "Bol su ve sabunla yıkayın.", en: "Wash with plenty of soap and water." },
    inhaled: { tr: "Temiz havaya çıkarın.", en: "Move to fresh air." },
    swallowed: { tr: "Ağzı çalkalatın, su içirin. Şikâyet sürerse tıbbi yardım alın.", en: "Rinse the mouth and give water. Get medical help if symptoms persist." },
  },
  low: {
    eyes: { tr: "Suyla yıkayın.", en: "Rinse with water." },
    skin: { tr: "Su ve sabunla yıkayın.", en: "Wash with soap and water." },
    inhaled: { tr: "Temiz havaya çıkarın.", en: "Move to fresh air." },
    swallowed: { tr: "Ağzı çalkalatın. Rahatsızlık sürerse tıbbi yardım alın.", en: "Rinse the mouth. Get medical help if you feel unwell." },
  },
};

export const STORAGE: Record<StorageProfile, { tr: string; en: string }> = {
  corrosive: {
    tr: "Asit/baz dolabında, kendi sınıfıyla birlikte ve göz hizasının altında. Karşıt sınıfla (asit ↔ baz) aynı rafta durmaz. İkincil kap kullanın.",
    en: "In a corrosives cabinet with its own class, below eye level. Never on the same shelf as the opposite class (acid vs base). Use secondary containment.",
  },
  flammable: {
    tr: "Onaylı alevlenir madde dolabında, tutuşturucu kaynaklardan uzakta, serin ve havalandırılan yerde. Buzdolabına konacaksa yalnızca kıvılcım korumalı laboratuvar tipi olana.",
    en: "In an approved flammables cabinet, away from ignition sources, cool and ventilated. If refrigerated, only in a spark-free laboratory refrigerator.",
  },
  oxidiser: {
    tr: "Alevlenir ve organik maddelerden ayrı bir dolapta. Ahşap raf ve karton kutu kullanmayın.",
    en: "In a separate cabinet, away from flammables and organic materials. Avoid wooden shelving and cardboard.",
  },
  toxic: {
    tr: "Kilitli dolapta, kayıt tutularak. Havalandırılan yerde ve ikincil kapta; erişim sınırlı olmalı.",
    en: "In a locked cabinet with an inventory record. Ventilated, in secondary containment, with restricted access.",
  },
  reactive: {
    tr: "Nem ve havadan yalıtılmış: inert gaz altında veya mineral yağ içinde, kuru bir dolapta. Sudan uzak.",
    en: "Isolated from air and moisture: under inert gas or mineral oil, in a dry cabinet. Away from water.",
  },
  ambient: { tr: "Oda sıcaklığında, kuru ve kapalı kapta.", en: "At room temperature, dry, in a closed container." },
  cold: { tr: "Buzdolabında (2-8 °C), ışıktan korunmuş ve kapalı kapta.", en: "Refrigerated (2-8 °C), protected from light, in a closed container." },
};

export const CHEMICALS: SafetyChemical[] = [
  // --- Acids ---
  {
    id: "hydrochloric-acid",
    name: "Hydrochloric acid (37%)",
    nameTr: "Hidroklorik asit (%37)",
    formula: "HCl",
    cas: "7647-01-0",
    synonyms: ["muriatic acid", "tuz ruhu", "hidroklorik"],
    category: "acid",
    pictograms: ["corrosive", "harmful"],
    signal: "danger",
    hazards: ["H290", "H314", "H335"],
    precautions: ["P260", "P280", "P303+P361+P353", "P305+P351+P338", "P304+P340", "P310"],
    firstAid: "corrosive",
    storage: "corrosive",
    incompatible: ["strongBases", "oxidisers", "metals", "cyanides"],
    note: {
      tr: "Seyreltirken daima asidi suya ekleyin. Hipoklorit ile karıştırılırsa klor gazı açığa çıkar.",
      en: "Always add acid to water when diluting. Mixing with hypochlorite releases chlorine gas.",
    },
  },
  {
    id: "sulfuric-acid",
    name: "Sulfuric acid (conc.)",
    nameTr: "Sülfürik asit (derişik)",
    formula: "H₂SO₄",
    cas: "7664-93-9",
    synonyms: ["oil of vitriol", "zaç yağı", "sulfurik"],
    category: "acid",
    pictograms: ["corrosive"],
    signal: "danger",
    hazards: ["H290", "H314"],
    precautions: ["P260", "P280", "P303+P361+P353", "P305+P351+P338", "P310", "P501"],
    firstAid: "corrosive",
    storage: "corrosive",
    incompatible: ["water", "strongBases", "oxidisers", "metals", "organics"],
    note: {
      tr: "Suyla seyreltilmesi çok ısı verir: asidi suya, yavaşça ve karıştırarak ekleyin. Asla tersi değil.",
      en: "Dilution releases a great deal of heat: add the acid to the water slowly, with stirring. Never the other way round.",
    },
  },
  {
    id: "nitric-acid",
    name: "Nitric acid (65%)",
    nameTr: "Nitrik asit (%65)",
    formula: "HNO₃",
    cas: "7697-37-2",
    synonyms: ["aqua fortis", "kezzap", "nitrik"],
    category: "acid",
    pictograms: ["oxidising", "corrosive", "toxic"],
    signal: "danger",
    hazards: ["H272", "H290", "H314", "H331"],
    precautions: ["P210", "P260", "P280", "P303+P361+P353", "P305+P351+P338", "P304+P340", "P310"],
    firstAid: "corrosive",
    storage: "corrosive",
    incompatible: ["organics", "strongBases", "metals", "reducers"],
    note: {
      tr: "Organik maddelerle (aseton, alkol, talaş) şiddetli tepkir. Ciltte sarı leke (ksantoproteik) bırakır.",
      en: "Reacts violently with organics (acetone, alcohols, sawdust). Leaves a yellow stain on skin (xanthoproteic).",
    },
  },
  {
    id: "acetic-acid",
    name: "Acetic acid (glacial)",
    nameTr: "Asetik asit (buzlu)",
    formula: "CH₃COOH",
    cas: "64-19-7",
    synonyms: ["ethanoic acid", "sirke asidi", "glacial"],
    category: "acid",
    pictograms: ["flammable", "corrosive"],
    signal: "danger",
    hazards: ["H226", "H290", "H314"],
    precautions: ["P210", "P280", "P303+P361+P353", "P305+P351+P338", "P310", "P403+P233"],
    firstAid: "corrosive",
    storage: "corrosive",
    incompatible: ["strongBases", "oxidisers", "metals"],
    note: { tr: "16 °C altında donar; donmuş şişeyi ısıtırken kap çatlayabilir.", en: "Freezes below 16 °C; a frozen bottle can crack when warmed." },
  },
  {
    id: "phosphoric-acid",
    name: "Phosphoric acid (85%)",
    nameTr: "Fosforik asit (%85)",
    formula: "H₃PO₄",
    cas: "7664-38-2",
    synonyms: ["orthophosphoric acid", "fosforik"],
    category: "acid",
    pictograms: ["corrosive"],
    signal: "danger",
    hazards: ["H290", "H314"],
    precautions: ["P260", "P280", "P303+P361+P353", "P305+P351+P338", "P310"],
    firstAid: "corrosive",
    storage: "corrosive",
    incompatible: ["strongBases", "metals"],
  },
  {
    id: "formic-acid",
    name: "Formic acid",
    nameTr: "Formik asit",
    formula: "HCOOH",
    cas: "64-18-6",
    synonyms: ["methanoic acid", "karınca asidi"],
    category: "acid",
    pictograms: ["flammable", "corrosive", "toxic"],
    signal: "danger",
    hazards: ["H226", "H302", "H314", "H331"],
    precautions: ["P210", "P260", "P280", "P303+P361+P353", "P305+P351+P338", "P304+P340", "P310"],
    firstAid: "corrosive",
    storage: "corrosive",
    incompatible: ["strongBases", "oxidisers"],
  },

  // --- Bases ---
  {
    id: "sodium-hydroxide",
    name: "Sodium hydroxide",
    nameTr: "Sodyum hidroksit",
    formula: "NaOH",
    cas: "1310-73-2",
    synonyms: ["caustic soda", "kostik", "sud kostik"],
    category: "base",
    pictograms: ["corrosive"],
    signal: "danger",
    hazards: ["H290", "H314"],
    precautions: ["P260", "P280", "P303+P361+P353", "P305+P351+P338", "P310", "P501"],
    firstAid: "corrosive",
    storage: "corrosive",
    incompatible: ["strongAcids", "metals", "water", "organics"],
    note: {
      tr: "Suda çözünmesi çok ısı verir; pelletleri suya azar azar ekleyin. Havadan nem ve CO₂ çeker.",
      en: "Dissolving releases a great deal of heat; add pellets to water a little at a time. Absorbs moisture and CO₂ from the air.",
    },
  },
  {
    id: "potassium-hydroxide",
    name: "Potassium hydroxide",
    nameTr: "Potasyum hidroksit",
    formula: "KOH",
    cas: "1310-58-3",
    synonyms: ["caustic potash", "potas kostik"],
    category: "base",
    pictograms: ["corrosive", "harmful"],
    signal: "danger",
    hazards: ["H290", "H302", "H314"],
    precautions: ["P260", "P280", "P301+P330+P331", "P303+P361+P353", "P305+P351+P338", "P310"],
    firstAid: "corrosive",
    storage: "corrosive",
    incompatible: ["strongAcids", "metals", "water"],
  },
  {
    id: "ammonia-solution",
    name: "Ammonia solution (25%)",
    nameTr: "Amonyak çözeltisi (%25)",
    formula: "NH₄OH",
    cas: "1336-21-6",
    synonyms: ["ammonium hydroxide", "amonyak", "nişadır ruhu"],
    category: "base",
    pictograms: ["corrosive", "harmful", "environment"],
    signal: "danger",
    hazards: ["H290", "H314", "H335", "H400"],
    precautions: ["P260", "P273", "P280", "P303+P361+P353", "P305+P351+P338", "P304+P340", "P310"],
    firstAid: "corrosive",
    storage: "corrosive",
    incompatible: ["strongAcids", "oxidisers", "halogens", "metals"],
    note: {
      tr: "Hipoklorit (çamaşır suyu) ile karıştırılırsa toksik kloramin gazı açığa çıkar. Şişeyi çeker ocakta açın.",
      en: "Mixing with hypochlorite (bleach) releases toxic chloramine gas. Open the bottle in a fume hood.",
    },
  },
  {
    id: "calcium-hydroxide",
    name: "Calcium hydroxide",
    nameTr: "Kalsiyum hidroksit",
    formula: "Ca(OH)₂",
    cas: "1305-62-0",
    synonyms: ["slaked lime", "sönmüş kireç", "kireç"],
    category: "base",
    pictograms: ["corrosive", "harmful"],
    signal: "danger",
    hazards: ["H315", "H318", "H335"],
    precautions: ["P261", "P280", "P302+P352", "P305+P351+P338", "P310"],
    firstAid: "corrosive",
    storage: "ambient",
    incompatible: ["strongAcids"],
  },

  // --- Solvents ---
  {
    id: "acetone",
    name: "Acetone",
    nameTr: "Aseton",
    formula: "C₃H₆O",
    cas: "67-64-1",
    synonyms: ["propanone", "dimethyl ketone"],
    category: "solvent",
    pictograms: ["flammable", "harmful"],
    signal: "danger",
    hazards: ["H225", "H319", "H336"],
    precautions: ["P210", "P233", "P240", "P280", "P305+P351+P338", "P403+P233"],
    firstAid: "solvent",
    storage: "flammable",
    incompatible: ["oxidisers", "strongAcids", "strongBases"],
    note: {
      tr: "Buharı havadan ağırdır, tezgâh boyunca yayılıp uzaktaki bir kıvılcımdan tutuşabilir. Nitrik asitle şiddetli tepkir.",
      en: "The vapour is heavier than air, travels along the bench and can ignite from a distant spark. Reacts violently with nitric acid.",
    },
  },
  {
    id: "methanol",
    name: "Methanol",
    nameTr: "Metanol",
    formula: "CH₃OH",
    cas: "67-56-1",
    synonyms: ["methyl alcohol", "wood alcohol", "metil alkol"],
    category: "solvent",
    pictograms: ["flammable", "toxic", "health"],
    signal: "danger",
    hazards: ["H225", "H301", "H311", "H331", "H370"],
    precautions: ["P210", "P260", "P280", "P302+P352", "P304+P340", "P301+P310", "P403+P233"],
    firstAid: "toxic",
    storage: "flammable",
    incompatible: ["oxidisers", "strongAcids", "metals"],
    note: {
      tr: "Az miktarı bile körlüğe ve ölüme yol açar; deriden de emilir. Etanolle karıştırılmaması için etiketi mutlaka kontrol edin.",
      en: "Even a small amount causes blindness and death; it is also absorbed through the skin. Always check the label so it is not confused with ethanol.",
    },
  },
  {
    id: "ethanol",
    name: "Ethanol (absolute)",
    nameTr: "Etanol (mutlak)",
    formula: "C₂H₅OH",
    cas: "64-17-5",
    synonyms: ["ethyl alcohol", "etil alkol", "alkol"],
    category: "solvent",
    pictograms: ["flammable", "harmful"],
    signal: "danger",
    hazards: ["H225", "H319"],
    precautions: ["P210", "P233", "P240", "P280", "P305+P351+P338", "P403+P233"],
    firstAid: "solvent",
    storage: "flammable",
    incompatible: ["oxidisers", "strongAcids"],
    note: {
      tr: "Alevi gündüz ışığında neredeyse görünmezdir; yanan bir kabı fark etmek zordur.",
      en: "The flame is nearly invisible in daylight, so a burning vessel is easy to miss.",
    },
  },
  {
    id: "isopropanol",
    name: "Isopropanol",
    nameTr: "İzopropanol",
    formula: "C₃H₈O",
    cas: "67-63-0",
    synonyms: ["2-propanol", "IPA", "izopropil alkol"],
    category: "solvent",
    pictograms: ["flammable", "harmful"],
    signal: "danger",
    hazards: ["H225", "H319", "H336"],
    precautions: ["P210", "P233", "P280", "P305+P351+P338", "P403+P233"],
    firstAid: "solvent",
    storage: "flammable",
    incompatible: ["oxidisers", "strongAcids"],
  },
  {
    id: "diethyl-ether",
    name: "Diethyl ether",
    nameTr: "Dietil eter",
    formula: "(C₂H₅)₂O",
    cas: "60-29-7",
    synonyms: ["ether", "ethoxyethane", "eter"],
    category: "solvent",
    pictograms: ["flammable", "harmful"],
    signal: "danger",
    hazards: ["H224", "H302", "H336"],
    precautions: ["P210", "P233", "P240", "P241", "P280", "P403+P235"],
    firstAid: "solvent",
    storage: "flammable",
    incompatible: ["oxidisers", "air", "light"],
    note: {
      tr: "Havayla temas eden eski şişelerde patlayıcı peroksit birikir. Açılış tarihini yazın, kuru kalıntı görürseniz şişeyi açmayın.",
      en: "Old bottles exposed to air build up explosive peroxides. Date the bottle on opening, and do not open one with dry residue.",
    },
  },
  {
    id: "dichloromethane",
    name: "Dichloromethane",
    nameTr: "Diklorometan",
    formula: "CH₂Cl₂",
    cas: "75-09-2",
    synonyms: ["DCM", "methylene chloride", "metilen klorür"],
    category: "solvent",
    pictograms: ["harmful", "health"],
    signal: "warning",
    hazards: ["H315", "H319", "H335", "H336", "H351"],
    precautions: ["P261", "P271", "P280", "P302+P352", "P305+P351+P338", "P403+P233"],
    firstAid: "solvent",
    storage: "flammable",
    incompatible: ["strongBases", "metals", "oxidisers"],
    note: {
      tr: "Çeker ocak dışında kullanmayın. Nitril eldiveni hızla geçer; kalın butil veya laminat eldiven gerekir.",
      en: "Do not use outside a fume hood. It permeates nitrile gloves quickly; thick butyl or laminate gloves are needed.",
    },
  },
  {
    id: "chloroform",
    name: "Chloroform",
    nameTr: "Kloroform",
    formula: "CHCl₃",
    cas: "67-66-3",
    synonyms: ["trichloromethane", "triklorometan"],
    category: "solvent",
    pictograms: ["toxic", "health"],
    signal: "danger",
    hazards: ["H302", "H315", "H319", "H331", "H351", "H372"],
    precautions: ["P261", "P271", "P280", "P304+P340", "P305+P351+P338", "P310", "P403+P233"],
    firstAid: "toxic",
    storage: "toxic",
    incompatible: ["strongBases", "metals", "oxidisers"],
    note: {
      tr: "Işık ve hava altında fosgen oluşturur; koyu şişede, stabilizatörlü saklayın.",
      en: "Forms phosgene on exposure to light and air; keep in a dark bottle with its stabiliser.",
    },
  },
  {
    id: "toluene",
    name: "Toluene",
    nameTr: "Toluen",
    formula: "C₇H₈",
    cas: "108-88-3",
    synonyms: ["methylbenzene", "toluol"],
    category: "solvent",
    pictograms: ["flammable", "harmful", "health"],
    signal: "danger",
    hazards: ["H225", "H304", "H315", "H336", "H361", "H373"],
    precautions: ["P210", "P260", "P280", "P301+P310", "P302+P352", "P403+P233"],
    firstAid: "solvent",
    storage: "flammable",
    incompatible: ["oxidisers", "strongAcids"],
  },
  {
    id: "hexane",
    name: "n-Hexane",
    nameTr: "n-Hekzan",
    formula: "C₆H₁₄",
    cas: "110-54-3",
    synonyms: ["hexane", "hekzan"],
    category: "solvent",
    pictograms: ["flammable", "harmful", "health", "environment"],
    signal: "danger",
    hazards: ["H225", "H304", "H315", "H336", "H361", "H373", "H411"],
    precautions: ["P210", "P273", "P280", "P301+P310", "P302+P352", "P403+P233"],
    firstAid: "solvent",
    storage: "flammable",
    incompatible: ["oxidisers"],
    note: {
      tr: "Tekrarlı maruz kalma sinir hasarı (periferik nöropati) yapar; izomer karışımı olan teknik hekzan daha az risklidir.",
      en: "Repeated exposure causes nerve damage (peripheral neuropathy); technical hexane, an isomer mixture, carries less risk.",
    },
  },
  {
    id: "ethyl-acetate",
    name: "Ethyl acetate",
    nameTr: "Etil asetat",
    formula: "C₄H₈O₂",
    cas: "141-78-6",
    synonyms: ["EtOAc", "acetic ester"],
    category: "solvent",
    pictograms: ["flammable", "harmful"],
    signal: "danger",
    hazards: ["H225", "H319", "H336"],
    precautions: ["P210", "P233", "P240", "P280", "P305+P351+P338", "P403+P233"],
    firstAid: "solvent",
    storage: "flammable",
    incompatible: ["oxidisers", "strongBases", "strongAcids"],
  },
  {
    id: "acetonitrile",
    name: "Acetonitrile",
    nameTr: "Asetonitril",
    formula: "CH₃CN",
    cas: "75-05-8",
    synonyms: ["ACN", "methyl cyanide"],
    category: "solvent",
    pictograms: ["flammable", "harmful"],
    signal: "danger",
    hazards: ["H225", "H302", "H312", "H319", "H332"],
    precautions: ["P210", "P261", "P280", "P302+P352", "P305+P351+P338", "P403+P233"],
    firstAid: "toxic",
    storage: "flammable",
    incompatible: ["oxidisers", "strongAcids", "strongBases"],
    note: {
      tr: "Vücutta siyanüre dönüşür; belirtiler saatler sonra çıkabilir. Maruz kalmada gecikmeden tıbbi yardım alın.",
      en: "It is metabolised to cyanide and symptoms can appear hours later. Seek medical help promptly after exposure.",
    },
  },
  {
    id: "dmso",
    name: "Dimethyl sulfoxide",
    nameTr: "Dimetil sülfoksit",
    formula: "C₂H₆OS",
    cas: "67-68-5",
    synonyms: ["DMSO"],
    category: "solvent",
    pictograms: ["harmful"],
    signal: "warning",
    hazards: ["H315", "H319"],
    precautions: ["P264", "P280", "P302+P352", "P305+P351+P338", "P337+P313"],
    firstAid: "irritant",
    storage: "ambient",
    incompatible: ["oxidisers", "strongAcids"],
    note: {
      tr: "Deriden hızla emilir ve içinde çözünmüş her şeyi birlikte taşır; toksik madde çözülmüş DMSO'ya çıplak elle dokunmayın.",
      en: "It is absorbed rapidly through skin and carries whatever is dissolved in it along; never touch DMSO containing a toxic solute with bare hands.",
    },
  },
  {
    id: "dmf",
    name: "N,N-Dimethylformamide",
    nameTr: "N,N-Dimetilformamit",
    formula: "C₃H₇NO",
    cas: "68-12-2",
    synonyms: ["DMF"],
    category: "solvent",
    pictograms: ["flammable", "harmful", "health"],
    signal: "danger",
    hazards: ["H226", "H312", "H319", "H332", "H360"],
    precautions: ["P201", "P210", "P280", "P302+P352", "P305+P351+P338", "P308+P313"],
    firstAid: "toxic",
    storage: "flammable",
    incompatible: ["oxidisers", "strongBases", "halogens"],
  },
  {
    id: "thf",
    name: "Tetrahydrofuran",
    nameTr: "Tetrahidrofuran",
    formula: "C₄H₈O",
    cas: "109-99-9",
    synonyms: ["THF", "oxolane"],
    category: "solvent",
    pictograms: ["flammable", "harmful", "health"],
    signal: "danger",
    hazards: ["H225", "H319", "H335", "H351"],
    precautions: ["P210", "P261", "P280", "P305+P351+P338", "P403+P233"],
    firstAid: "solvent",
    storage: "flammable",
    incompatible: ["oxidisers", "air", "light"],
    note: {
      tr: "Eter gibi peroksit biriktirir. Damıtmadan önce peroksit testi yapın; kuruluğa kadar damıtmayın.",
      en: "Like ether, it accumulates peroxides. Test for peroxides before distilling, and never distil to dryness.",
    },
  },
  {
    id: "xylene",
    name: "Xylene",
    nameTr: "Ksilen",
    formula: "C₈H₁₀",
    cas: "1330-20-7",
    synonyms: ["dimethylbenzene", "ksilol"],
    category: "solvent",
    pictograms: ["flammable", "harmful"],
    signal: "danger",
    hazards: ["H226", "H312", "H315", "H332"],
    precautions: ["P210", "P261", "P280", "P302+P352", "P304+P340", "P403+P233"],
    firstAid: "solvent",
    storage: "flammable",
    incompatible: ["oxidisers", "strongAcids"],
  },
  {
    id: "benzene",
    name: "Benzene",
    nameTr: "Benzen",
    formula: "C₆H₆",
    cas: "71-43-2",
    synonyms: ["benzol"],
    category: "solvent",
    pictograms: ["flammable", "harmful", "health"],
    signal: "danger",
    hazards: ["H225", "H304", "H315", "H319", "H340", "H350", "H372"],
    precautions: ["P201", "P210", "P280", "P301+P310", "P308+P313", "P403+P233"],
    firstAid: "toxic",
    storage: "toxic",
    incompatible: ["oxidisers", "halogens"],
    note: {
      tr: "Kanıtlanmış lösemi etkeni. Güvenli maruz kalma eşiği yoktur; mümkünse toluenle değiştirin.",
      en: "A proven cause of leukaemia. There is no safe exposure threshold; substitute toluene where possible.",
    },
  },

  // --- Oxidisers ---
  {
    id: "hydrogen-peroxide",
    name: "Hydrogen peroxide (30%)",
    nameTr: "Hidrojen peroksit (%30)",
    formula: "H₂O₂",
    cas: "7722-84-1",
    synonyms: ["perhydrol", "oksijenli su"],
    category: "oxidiser",
    pictograms: ["oxidising", "corrosive", "harmful"],
    signal: "danger",
    hazards: ["H271", "H302", "H314", "H332", "H335"],
    precautions: ["P210", "P260", "P280", "P303+P361+P353", "P305+P351+P338", "P310", "P403+P235"],
    firstAid: "corrosive",
    storage: "oxidiser",
    incompatible: ["organics", "metals", "reducers", "strongBases", "heat"],
    note: {
      tr: "Havalandırma delikli kapakla saklanır: bozunurken oksijen üretir ve kapalı şişede basınç yapar.",
      en: "Store with a vented cap: it decomposes to oxygen and builds pressure in a sealed bottle.",
    },
  },
  {
    id: "potassium-permanganate",
    name: "Potassium permanganate",
    nameTr: "Potasyum permanganat",
    formula: "KMnO₄",
    cas: "7722-64-7",
    synonyms: ["permanganate", "permanganat"],
    category: "oxidiser",
    pictograms: ["oxidising", "harmful", "environment"],
    signal: "danger",
    hazards: ["H272", "H302", "H410"],
    precautions: ["P210", "P273", "P280", "P301+P330+P331", "P501"],
    firstAid: "irritant",
    storage: "oxidiser",
    incompatible: ["organics", "reducers", "strongAcids", "metals"],
    note: {
      tr: "Gliserin gibi organiklerle temasta kendiliğinden tutuşur. Kâğıt havluya dökmeyin.",
      en: "Ignites spontaneously on contact with organics such as glycerol. Do not wipe spills with paper towel.",
    },
  },
  {
    id: "potassium-dichromate",
    name: "Potassium dichromate",
    nameTr: "Potasyum dikromat",
    formula: "K₂Cr₂O₇",
    cas: "7778-50-9",
    synonyms: ["dichromate", "dikromat"],
    category: "oxidiser",
    pictograms: ["oxidising", "corrosive", "toxic", "health", "environment"],
    signal: "danger",
    hazards: ["H272", "H301", "H312", "H314", "H317", "H330", "H334", "H340", "H350", "H360", "H372", "H410"],
    precautions: ["P201", "P210", "P260", "P273", "P280", "P284", "P301+P310", "P305+P351+P338", "P405", "P501"],
    firstAid: "toxic",
    storage: "toxic",
    incompatible: ["organics", "reducers", "strongAcids"],
    note: {
      tr: "Cr(VI) kanserojendir. Kromik asit temizleme çözeltisi artık önerilmez; yerine alkali temizleyici kullanın.",
      en: "Cr(VI) is carcinogenic. Chromic acid cleaning solution is no longer recommended; use an alkaline cleaner instead.",
    },
  },
  {
    id: "sodium-hypochlorite",
    name: "Sodium hypochlorite (bleach)",
    nameTr: "Sodyum hipoklorit (çamaşır suyu)",
    formula: "NaOCl",
    cas: "7681-52-9",
    synonyms: ["bleach", "çamaşır suyu", "hipoklorit"],
    category: "oxidiser",
    pictograms: ["corrosive", "environment"],
    signal: "danger",
    hazards: ["H290", "H314", "H400"],
    precautions: ["P260", "P273", "P280", "P303+P361+P353", "P305+P351+P338", "P310", "P501"],
    firstAid: "corrosive",
    storage: "corrosive",
    incompatible: ["strongAcids", "ammonia", "organics", "metals", "light"],
    note: {
      tr: "Asitle klor, amonyakla kloramin gazı verir. Asla başka temizleyiciyle karıştırmayın.",
      en: "Gives chlorine with acid and chloramine with ammonia. Never mix it with another cleaner.",
    },
  },
  {
    id: "silver-nitrate",
    name: "Silver nitrate",
    nameTr: "Gümüş nitrat",
    formula: "AgNO₃",
    cas: "7761-88-8",
    synonyms: ["lunar caustic", "gümüş nitrat"],
    category: "oxidiser",
    pictograms: ["oxidising", "corrosive", "environment"],
    signal: "danger",
    hazards: ["H272", "H314", "H410"],
    precautions: ["P210", "P273", "P280", "P305+P351+P338", "P310", "P501"],
    firstAid: "corrosive",
    storage: "oxidiser",
    incompatible: ["organics", "reducers", "ammonia", "light"],
    note: {
      tr: "Ciltte ve tezgâhta kalıcı siyah leke bırakır. Amonyaklı çözeltileri bekletmeyin: patlayıcı gümüş nitrür oluşur.",
      en: "Leaves a permanent black stain on skin and bench. Do not store ammoniacal solutions: explosive silver nitride forms.",
    },
  },

  // --- Toxic substances ---
  {
    id: "sodium-azide",
    name: "Sodium azide",
    nameTr: "Sodyum azit",
    formula: "NaN₃",
    cas: "26628-22-8",
    synonyms: ["azide", "azit"],
    category: "toxic",
    pictograms: ["toxic", "environment"],
    signal: "danger",
    hazards: ["H300", "H310", "H410"],
    precautions: ["P262", "P264", "P273", "P280", "P301+P310", "P302+P352", "P405", "P501"],
    firstAid: "toxic",
    storage: "toxic",
    incompatible: ["strongAcids", "metals", "water"],
    note: {
      tr: "Lavaboya dökmeyin: kurşun ve bakır borularla patlayıcı metal azit oluşturur. Asitle çok toksik hidrazoik asit verir.",
      en: "Never pour down the drain: it forms explosive metal azides with lead and copper plumbing. With acid it gives highly toxic hydrazoic acid.",
    },
  },
  {
    id: "potassium-cyanide",
    name: "Potassium cyanide",
    nameTr: "Potasyum siyanür",
    formula: "KCN",
    cas: "151-50-8",
    synonyms: ["cyanide", "siyanür"],
    category: "toxic",
    pictograms: ["toxic", "environment"],
    signal: "danger",
    hazards: ["H290", "H300", "H310", "H330", "H410"],
    precautions: ["P260", "P264", "P273", "P280", "P284", "P301+P310", "P302+P352", "P405", "P501"],
    firstAid: "toxic",
    storage: "toxic",
    incompatible: ["strongAcids", "oxidisers", "water"],
    note: {
      tr: "Asitle temasta anında öldürücü hidrojen siyanür gazı çıkar. Yalnızca çeker ocakta, panzehir kiti ve ikinci bir kişi hazırken çalışılır.",
      en: "Contact with acid instantly releases lethal hydrogen cyanide gas. Work only in a fume hood, with an antidote kit and a second person present.",
    },
  },
  {
    id: "mercury-chloride",
    name: "Mercury(II) chloride",
    nameTr: "Cıva(II) klorür",
    formula: "HgCl₂",
    cas: "7487-94-7",
    synonyms: ["corrosive sublimate", "cıva klorür"],
    category: "toxic",
    pictograms: ["toxic", "corrosive", "health", "environment"],
    signal: "danger",
    hazards: ["H300", "H314", "H341", "H361", "H372", "H410"],
    precautions: ["P260", "P273", "P280", "P301+P310", "P305+P351+P338", "P405", "P501"],
    firstAid: "toxic",
    storage: "toxic",
    incompatible: ["metals", "strongBases", "reducers"],
  },
  {
    id: "phenol",
    name: "Phenol",
    nameTr: "Fenol",
    formula: "C₆H₅OH",
    cas: "108-95-2",
    synonyms: ["carbolic acid", "karbolik asit"],
    category: "toxic",
    pictograms: ["corrosive", "toxic", "health"],
    signal: "danger",
    hazards: ["H301", "H311", "H314", "H331", "H341", "H373"],
    precautions: ["P260", "P280", "P301+P310", "P302+P352", "P305+P351+P338", "P310", "P405"],
    firstAid: "toxic",
    storage: "toxic",
    incompatible: ["oxidisers", "strongBases"],
    note: {
      tr: "Deriyi uyuşturduğu için yanık hissedilmeden ilerler ve kandan emilir. Temas eden bölgeyi PEG 300 veya bol suyla hemen temizleyin.",
      en: "It numbs the skin, so a burn spreads unnoticed while it is absorbed into the blood. Clean the contact area immediately with PEG 300 or plenty of water.",
    },
  },
  {
    id: "formaldehyde",
    name: "Formaldehyde (37%)",
    nameTr: "Formaldehit (%37)",
    formula: "CH₂O",
    cas: "50-00-0",
    synonyms: ["formalin", "formol", "formalin"],
    category: "toxic",
    pictograms: ["corrosive", "toxic", "health"],
    signal: "danger",
    hazards: ["H301", "H311", "H314", "H317", "H331", "H335", "H341", "H350"],
    precautions: ["P201", "P260", "P280", "P301+P310", "P302+P352", "P305+P351+P338", "P405"],
    firstAid: "toxic",
    storage: "toxic",
    incompatible: ["oxidisers", "strongBases", "strongAcids"],
    note: {
      tr: "Kanserojen. Fiksasyon işlemleri çeker ocakta yapılmalı; ortam ölçümü gerektiren maddelerdendir.",
      en: "Carcinogenic. Fixation work belongs in a fume hood; it is one of the substances requiring workplace air monitoring.",
    },
  },
  {
    id: "ethidium-bromide",
    name: "Ethidium bromide",
    nameTr: "Etidyum bromür",
    formula: "C₂₁H₂₀BrN₃",
    cas: "1239-45-8",
    synonyms: ["EtBr", "etidyum"],
    category: "toxic",
    pictograms: ["toxic", "health"],
    signal: "danger",
    hazards: ["H302", "H330", "H341"],
    precautions: ["P260", "P264", "P280", "P284", "P301+P310", "P304+P340", "P405", "P501"],
    firstAid: "toxic",
    storage: "toxic",
    incompatible: ["oxidisers", "light"],
    note: {
      tr: "Mutajen: DNA'ya girer. Toz hâli en riskli formdur, çözelti olarak alın. Atığı aktif karbonla arıtılmadan dökülmez.",
      en: "Mutagenic: it intercalates into DNA. The powder is the riskiest form, so buy it as a solution. Waste must be treated with activated charcoal before disposal.",
    },
  },
  {
    id: "acrylamide",
    name: "Acrylamide",
    nameTr: "Akrilamit",
    formula: "C₃H₅NO",
    cas: "79-06-1",
    synonyms: ["acrylamide monomer", "akrilamid"],
    category: "toxic",
    pictograms: ["toxic", "health"],
    signal: "danger",
    hazards: ["H301", "H312", "H315", "H317", "H319", "H332", "H340", "H350", "H361", "H372"],
    precautions: ["P201", "P260", "P280", "P301+P310", "P302+P352", "P305+P351+P338", "P405"],
    firstAid: "toxic",
    storage: "toxic",
    incompatible: ["oxidisers", "strongAcids", "strongBases", "light"],
    note: {
      tr: "Sinir toksini ve kanserojen; tozunu solumamak için hazır jel çözeltisi tercih edilir. Polimerleşmiş jel çok daha az risklidir.",
      en: "A neurotoxin and carcinogen; prefer ready-made gel solutions to avoid the dust. The polymerised gel is far less hazardous.",
    },
  },

  // --- Reactive substances ---
  {
    id: "sodium-metal",
    name: "Sodium (metal)",
    nameTr: "Sodyum (metal)",
    formula: "Na",
    cas: "7440-23-5",
    synonyms: ["sodium metal", "metalik sodyum"],
    category: "reactive",
    pictograms: ["flammable", "corrosive"],
    signal: "danger",
    hazards: ["H260", "H314"],
    precautions: ["P223", "P231+P232", "P280", "P305+P351+P338", "P370+P378", "P422"],
    firstAid: "corrosive",
    storage: "reactive",
    incompatible: ["water", "strongAcids", "halogens", "air"],
    note: {
      tr: "Suyla temasta hidrojen açığa çıkarır ve tutuşur. Yangınına su veya CO₂ değil, D sınıfı kuru toz veya kuru kum kullanılır.",
      en: "Contact with water releases hydrogen and ignites. Fight a fire with class D dry powder or dry sand, never water or CO₂.",
    },
  },
  {
    id: "lithium-aluminium-hydride",
    name: "Lithium aluminium hydride",
    nameTr: "Lityum alüminyum hidrür",
    formula: "LiAlH₄",
    cas: "16853-85-3",
    synonyms: ["LAH", "LiAlH4"],
    category: "reactive",
    pictograms: ["flammable", "corrosive"],
    signal: "danger",
    hazards: ["H260", "H314"],
    precautions: ["P223", "P231+P232", "P280", "P305+P351+P338", "P370+P378", "P422"],
    firstAid: "corrosive",
    storage: "reactive",
    incompatible: ["water", "strongAcids", "air", "organics"],
    note: {
      tr: "Havadaki nem bile tutuşturur; tartım eldivenli kutuda veya inert akış altında yapılır. Söndürücü olarak yalnızca kuru toz.",
      en: "Even atmospheric moisture can ignite it; weigh in a glovebox or under inert flow. Use dry powder extinguishers only.",
    },
  },
  {
    id: "acetic-anhydride",
    name: "Acetic anhydride",
    nameTr: "Asetik anhidrit",
    formula: "(CH₃CO)₂O",
    cas: "108-24-7",
    synonyms: ["ethanoic anhydride"],
    category: "reactive",
    pictograms: ["flammable", "corrosive", "harmful"],
    signal: "danger",
    hazards: ["H226", "H302", "H314", "H331"],
    precautions: ["P210", "P260", "P280", "P303+P361+P353", "P305+P351+P338", "P304+P340", "P310"],
    firstAid: "corrosive",
    storage: "corrosive",
    incompatible: ["water", "strongBases", "oxidisers"],
  },

  // --- Salts and common solids ---
  {
    id: "copper-sulfate",
    name: "Copper(II) sulfate",
    nameTr: "Bakır(II) sülfat",
    formula: "CuSO₄·5H₂O",
    cas: "7758-98-7",
    synonyms: ["blue vitriol", "göztaşı", "bakır sülfat"],
    category: "salt",
    pictograms: ["corrosive", "harmful", "environment"],
    signal: "danger",
    hazards: ["H302", "H315", "H318", "H410"],
    precautions: ["P264", "P273", "P280", "P301+P330+P331", "P305+P351+P338", "P310", "P501"],
    firstAid: "irritant",
    storage: "ambient",
    incompatible: ["strongBases", "metals", "reducers"],
  },
  {
    id: "sds-detergent",
    name: "Sodium dodecyl sulfate",
    nameTr: "Sodyum dodesil sülfat",
    formula: "C₁₂H₂₅NaO₄S",
    cas: "151-21-3",
    synonyms: ["SDS", "lauryl sulfate", "SLS"],
    category: "biochem",
    pictograms: ["flammable", "corrosive", "harmful"],
    signal: "danger",
    hazards: ["H228", "H302", "H311", "H315", "H318", "H332", "H335"],
    precautions: ["P210", "P261", "P280", "P302+P352", "P305+P351+P338", "P310"],
    firstAid: "irritant",
    storage: "ambient",
    incompatible: ["oxidisers", "strongAcids"],
    note: {
      tr: "Tozu çok kolay havalanır ve solunum yolunu tahriş eder; tartımı çeker ocakta veya maskeli yapın.",
      en: "The powder becomes airborne easily and irritates the airways; weigh it in a hood or wear a mask.",
    },
  },
  {
    id: "tris-base",
    name: "Tris base",
    nameTr: "Tris baz",
    formula: "C₄H₁₁NO₃",
    cas: "77-86-1",
    synonyms: ["tromethamine", "THAM", "trizma"],
    category: "biochem",
    pictograms: ["harmful"],
    signal: "warning",
    hazards: ["H315", "H319", "H335"],
    precautions: ["P261", "P264", "P280", "P302+P352", "P305+P351+P338", "P337+P313"],
    firstAid: "irritant",
    storage: "ambient",
    incompatible: ["strongAcids", "oxidisers"],
  },
  {
    id: "edta",
    name: "EDTA disodium salt",
    nameTr: "EDTA disodyum tuzu",
    formula: "C₁₀H₁₄N₂Na₂O₈",
    cas: "6381-92-6",
    synonyms: ["EDTA", "versene", "edta"],
    category: "biochem",
    pictograms: ["harmful"],
    signal: "warning",
    hazards: ["H319"],
    precautions: ["P264", "P280", "P305+P351+P338", "P337+P313"],
    firstAid: "irritant",
    storage: "ambient",
    incompatible: ["oxidisers", "strongAcids"],
    note: {
      tr: "pH 8'e getirilmeden suda çözünmez; NaOH ile ayarlanır.",
      en: "It does not dissolve until the pH is brought to about 8, which is done with NaOH.",
    },
  },
  {
    id: "sodium-chloride",
    name: "Sodium chloride",
    nameTr: "Sodyum klorür",
    formula: "NaCl",
    cas: "7647-14-5",
    synonyms: ["table salt", "tuz", "yemek tuzu"],
    category: "salt",
    pictograms: [],
    signal: "none",
    hazards: [],
    precautions: ["P264"],
    firstAid: "low",
    storage: "ambient",
    incompatible: [],
    note: {
      tr: "GHS'ye göre tehlikeli sınıfta değil. Yine de laboratuvar kimyasalı gibi ele alınır: yiyecek olarak kullanılmaz.",
      en: "Not classified as hazardous under GHS. It is still treated as a laboratory chemical and never used as food.",
    },
  },
  {
    id: "sodium-bicarbonate",
    name: "Sodium bicarbonate",
    nameTr: "Sodyum bikarbonat",
    formula: "NaHCO₃",
    cas: "144-55-8",
    synonyms: ["baking soda", "karbonat", "kabartma tozu"],
    category: "salt",
    pictograms: [],
    signal: "none",
    hazards: [],
    precautions: ["P264"],
    firstAid: "low",
    storage: "ambient",
    incompatible: ["strongAcids"],
    note: {
      tr: "Asit döküntülerini nötralize etmek için kullanılır; köpürme biter bitmez bölge suyla yıkanır.",
      en: "Used to neutralise acid spills; once the fizzing stops the area is washed with water.",
    },
  },
  {
    id: "glucose",
    name: "D-Glucose",
    nameTr: "D-Glukoz",
    formula: "C₆H₁₂O₆",
    cas: "50-99-7",
    synonyms: ["dextrose", "glikoz", "dekstroz"],
    category: "biochem",
    pictograms: [],
    signal: "none",
    hazards: [],
    precautions: ["P264"],
    firstAid: "low",
    storage: "ambient",
    incompatible: ["oxidisers"],
  },
  {
    id: "agar",
    name: "Agar",
    nameTr: "Agar",
    formula: "-",
    cas: "9002-18-0",
    synonyms: ["agar-agar", "besiyeri agarı"],
    category: "biochem",
    pictograms: [],
    signal: "none",
    hazards: [],
    precautions: ["P264"],
    firstAid: "low",
    storage: "ambient",
    incompatible: [],
    note: {
      tr: "Tehlikeli değil, ama otoklavdan çıkan erimiş agar 90 °C'dir ve ciddi yanık yapar.",
      en: "Not hazardous, but molten agar straight from the autoclave is at 90 °C and causes serious burns.",
    },
  },
];

/** Matches name, Turkish name, formula, CAS or any synonym. */
export function searchChemicals(query: string): SafetyChemical[] {
  const q = query.trim().toLocaleLowerCase("tr");
  if (!q) return CHEMICALS;
  return CHEMICALS.filter((chemical) => {
    const haystack = [
      chemical.name,
      chemical.nameTr,
      chemical.formula,
      chemical.cas,
      ...chemical.synonyms,
    ]
      .join(" ")
      .toLocaleLowerCase("tr");
    return haystack.includes(q);
  });
}

export function chemicalById(id: string): SafetyChemical | undefined {
  return CHEMICALS.find((chemical) => chemical.id === id);
}
