#!/usr/bin/env python3
"""Generate the Chem+ app's image resources from the website's own brand files.

  public/seo/favicon.png   flask mark on #F6F7F8  -> launcher icons (adaptive, themed, legacy),
                                                     notification icon, Play Store icon
  public/images/logo.png   flask + "Chem+"        -> splash screen, offline screen logo
  public/chem-bg.webp      hero doodle backdrop   -> Play Store feature graphic
  lucide icons from the dashboard sidebar         -> launcher shortcut icons, offline icon

Usage:  python scripts/generate_icons.py [--web D:/targa/illustrae-clone]
Needs Pillow (pip install pillow).
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "android" / "app" / "src" / "main" / "res"
STORE = ROOT / "store"
DENSITIES = {"mdpi": 1.0, "hdpi": 1.5, "xhdpi": 2.0, "xxhdpi": 3.0, "xxxhdpi": 4.0}

ICON_BACKGROUND = (0xF6, 0xF7, 0xF8)  # favicon background; same as @color/icon_background
PLAY_ICON_MARK_PX = 384  # mark height inside the 512px Play icon (75%)
INK_NAVY = (0x06, 0x26, 0x3F)   # flask outline and molecule
INK_TEAL = (0x35, 0xA5, 0xA7)   # liquid and bubbles
LOGO_FLASK_CUT_X = 470          # right of the molecule arm, left of the wordmark's 'h'
LOGO_FLASK_EDGE_X = 395         # flask's own right edge, below the arm
LOGO_MOLECULE_BOTTOM_Y = 140    # where the arm ends and the 'C' begins
ICON_MARK_SOURCE = STORE / "source" / "icon-mark.png"  # optional hand-drawn mark, used when present
FEATURE_ART_SOURCE = STORE / "source" / "feature-art.png"  # optional hand-made banner, used when present
FEATURE_ART_SCALE = 0.87          # shrink it inside the frame so type clears Play's crop
FEATURE_DARK = (8, 28, 45)        # feature graphic gradient, top-left
FEATURE_LIGHT = (18, 62, 86)      # feature graphic gradient, bottom-right
FEATURE_TEXT = (244, 249, 250)
FEATURE_MUTED = (168, 198, 208)
FEATURE_MARGIN = 64               # Play crops the banner; keep content inside this
FEATURE_TAGLINE = "Kimya hesaplamaları, sanal laboratuvar ve lab defteri"
FEATURE_CHIPS = ("107 hesaplayıcı", "Sanal laboratuvar", "ChemDraw")
LOGO_WORDMARK_X = 405             # left edge of the "C"
LOGO_WORDMARK_Y = 150             # below the molecule arm that reaches over the lettering
FONT_REGULAR = "C:/Windows/Fonts/segoeui.ttf"
FONT_SEMIBOLD = "C:/Windows/Fonts/seguisb.ttf"
SHORTCUT_GLYPH = "@color/brand_purple"  # the site header's icon color
OFFLINE_GLYPH = "@color/text_secondary"

ADAPTIVE_DP = 108  # adaptive icon layer size
MARK_RADIUS_DP = 31.5  # launcher masks never cut inside the centered 66dp circle
LEGACY_DP = 48
SPLASH_WIDTH_DP = 200
NOTIFICATION_DP = 24
NOTIFICATION_CONTENT_DP = 20

# Lucide icons (ISC License, Copyright (c) Lucide Icons and Contributors), copied from
# lucide-react 1.23.0 - the same icons the website's dashboard sidebar uses.
LUCIDE = {
    "calculators": [
        ("rect", {"width": 16, "height": 20, "x": 4, "y": 2, "rx": 2}),
        ("line", {"x1": 8, "x2": 16, "y1": 6, "y2": 6}),
        ("line", {"x1": 16, "x2": 16, "y1": 14, "y2": 18}),
        ("path", {"d": "M16 10h.01"}),
        ("path", {"d": "M12 10h.01"}),
        ("path", {"d": "M8 10h.01"}),
        ("path", {"d": "M12 14h.01"}),
        ("path", {"d": "M8 14h.01"}),
        ("path", {"d": "M12 18h.01"}),
        ("path", {"d": "M8 18h.01"}),
    ],
    "virtual_lab": [  # flask-conical
        ("path", {"d": "M14 2v6a2 2 0 0 0 .245.96l5.51 10.08A2 2 0 0 1 18 22H6a2 2 0 0 1-1.755-2.96l5.51-10.08A2 2 0 0 0 10 8V2"}),
        ("path", {"d": "M6.453 15h11.094"}),
        ("path", {"d": "M8.5 2h7"}),
    ],
    "chemdraw": [  # pen-tool
        ("path", {"d": "M15.707 21.293a1 1 0 0 1-1.414 0l-1.586-1.586a1 1 0 0 1 0-1.414l5.586-5.586a1 1 0 0 1 1.414 0l1.586 1.586a1 1 0 0 1 0 1.414z"}),
        ("path", {"d": "m18 13-1.375-6.874a1 1 0 0 0-.746-.776L3.235 2.028a1 1 0 0 0-1.207 1.207L5.35 15.879a1 1 0 0 0 .776.746L13 18"}),
        ("path", {"d": "m2.3 2.3 7.286 7.286"}),
        ("circle", {"cx": 11, "cy": 11, "r": 2}),
    ],
    "wifi_off": [
        ("path", {"d": "M12 20h.01"}),
        ("path", {"d": "M8.5 16.429a5 5 0 0 1 7 0"}),
        ("path", {"d": "M5 12.859a10 10 0 0 1 5.17-2.69"}),
        ("path", {"d": "M19 12.859a10 10 0 0 0-2.007-1.523"}),
        ("path", {"d": "M2 8.82a15 15 0 0 1 4.177-2.643"}),
        ("path", {"d": "M22 8.82a15 15 0 0 0-11.288-3.764"}),
        ("path", {"d": "m2 2 20 20"}),
    ],
}

GENERATED_NOTICE = "<!-- Generated by scripts/generate_icons.py - edit the script, not this file. -->\n"


# ---------------------------------------------------------------------------------------------
# Raster helpers


def px(dp: float, density: float) -> int:
    return int(round(dp * density))


def write_png(image: Image.Image, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path, optimize=True)
    print(f"  {path.relative_to(ROOT)}  {image.size[0]}x{image.size[1]}")


def extract_mark(favicon: Image.Image) -> Image.Image:
    """Cut the flask out of its flat background.

    Alpha grows with the color distance to the background and colors are un-blended, so drawing
    the result over ICON_BACKGROUND gives back the favicon.
    """
    src = favicon.convert("RGB")
    out = Image.new("RGBA", src.size)
    sp, op = src.load(), out.load()
    noise, solid = 4.0, 48.0
    for y in range(src.size[1]):
        for x in range(src.size[0]):
            rgb = sp[x, y]
            dist = math.dist(rgb, ICON_BACKGROUND)
            if dist <= noise:
                op[x, y] = (0, 0, 0, 0)
                continue
            alpha = min(1.0, (dist - noise) / (solid - noise))
            color = tuple(
                max(0, min(255, round(bg + (c - bg) / alpha))) for c, bg in zip(rgb, ICON_BACKGROUND)
            )
            op[x, y] = (*color, round(alpha * 255))
    return out


def visible_bbox(image: Image.Image) -> tuple[int, int, int, int]:
    return image.getchannel("A").point(lambda a: 255 if a > 24 else 0).getbbox()


def farthest_pixel(image: Image.Image, cx: float, cy: float) -> float:
    alpha = image.getchannel("A").load()
    w, h = image.size
    return max(
        math.hypot(x - cx, y - cy) for y in range(h) for x in range(w) if alpha[x, y] > 24
    )


def place(image: Image.Image, size: int, center: tuple[float, float], scale: float) -> Image.Image:
    """Scale `image` and put its point `center` in the middle of a transparent size x size canvas."""
    scaled = image.resize(
        (max(1, round(image.width * scale)), max(1, round(image.height * scale))), Image.LANCZOS
    )
    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    left = round(size / 2 - center[0] * scale)
    top = round(size / 2 - center[1] * scale)
    # alpha_composite rejects negative destinations, so skip the part that falls off instead.
    canvas.alpha_composite(scaled, (max(0, left), max(0, top)), (max(0, -left), max(0, -top)))
    return canvas


def silhouette(image: Image.Image, color=(255, 255, 255)) -> Image.Image:
    out = Image.new("RGBA", image.size, (*color, 0))
    out.putalpha(image.getchannel("A"))
    return out


def smooth_mask(size: int, draw_shape, supersample: int = 4) -> Image.Image:
    big = Image.new("L", (size * supersample, size * supersample), 0)
    draw_shape(ImageDraw.Draw(big), size * supersample)
    return big.resize((size, size), Image.LANCZOS)


# ---------------------------------------------------------------------------------------------
# Launcher, notification, splash and store images


def launcher_icons(mark: Image.Image) -> None:
    bbox = visible_bbox(mark)
    center = ((bbox[0] + bbox[2]) / 2, (bbox[1] + bbox[3]) / 2)
    reach = farthest_pixel(mark, *center)
    print(f"mark bbox={bbox} center={center} reach={reach:.1f}px")

    for name, density in DENSITIES.items():
        size = px(ADAPTIVE_DP, density)
        scale = MARK_RADIUS_DP * density / reach
        foreground = place(mark, size, center, scale)
        write_png(foreground, RES / f"mipmap-{name}" / "ic_launcher_foreground.png")
        write_png(silhouette(foreground), RES / f"mipmap-{name}" / "ic_launcher_monochrome.png")

        # Pre-Oreo launchers get the adaptive icon's visible 72dp area in a fixed shape.
        full = Image.new("RGBA", (size, size), (*ICON_BACKGROUND, 255))
        full.alpha_composite(foreground)
        visible = px(72, density)
        offset = (size - visible) // 2
        visible_area = full.crop((offset, offset, offset + visible, offset + visible))
        legacy = px(LEGACY_DP, density)
        inner = px(LEGACY_DP - 4, density)
        body = visible_area.resize((inner, inner), Image.LANCZOS)
        for suffix, shape in (
            ("", lambda d, s: d.rounded_rectangle((0, 0, s - 1, s - 1), radius=s * 0.22, fill=255)),
            ("_round", lambda d, s: d.ellipse((0, 0, s - 1, s - 1), fill=255)),
        ):
            shaped = body.copy()
            shaped.putalpha(smooth_mask(inner, shape))
            icon = Image.new("RGBA", (legacy, legacy), (0, 0, 0, 0))
            icon.alpha_composite(shaped, ((legacy - inner) // 2, (legacy - inner) // 2))
            write_png(icon, RES / f"mipmap-{name}" / f"ic_launcher{suffix}.png")

    anydpi = RES / "mipmap-anydpi-v26"
    anydpi.mkdir(parents=True, exist_ok=True)
    adaptive = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        + GENERATED_NOTICE
        + '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@color/icon_background" />\n'
        '    <foreground android:drawable="@mipmap/ic_launcher_foreground" />\n'
        '    <monochrome android:drawable="@mipmap/ic_launcher_monochrome" />\n'
        "</adaptive-icon>\n"
    )
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        (anydpi / name).write_text(adaptive, encoding="utf-8")
        print(f"  {(anydpi / name).relative_to(ROOT)}")


def notification_icon(mark: Image.Image) -> None:
    bbox = visible_bbox(mark)
    center = ((bbox[0] + bbox[2]) / 2, (bbox[1] + bbox[3]) / 2)
    extent = max(bbox[2] - bbox[0], bbox[3] - bbox[1])
    for name, density in DENSITIES.items():
        size = px(NOTIFICATION_DP, density)
        scale = px(NOTIFICATION_CONTENT_DP, density) / extent
        write_png(silhouette(place(mark, size, center, scale)), RES / f"drawable-{name}" / "ic_notification.png")


def splash(logo: Image.Image) -> None:
    logo = logo.convert("RGBA").crop(visible_bbox(logo.convert("RGBA")))
    for name, density in DENSITIES.items():
        width = px(SPLASH_WIDTH_DP, density)
        height = round(logo.height * width / logo.width)
        write_png(logo.resize((width, height), Image.LANCZOS), RES / f"drawable-{name}" / "splash.png")


def flask_from_logo(logo: Image.Image) -> Image.Image:
    """The flask mark on its own, at the logo's resolution and with clean edges.

    The wordmark sits to the right of the flask but the molecule arm reaches over it, so the cut
    is a box rather than a single column. The logo's alpha is binary and its edges were flattened
    onto white first, which leaves a grey fringe; each pixel is matched back to the ink it came
    from and the coverage it had, so the mark scales down sharply instead of muddy."""
    art = logo.convert("RGBA").crop((0, 0, LOGO_FLASK_CUT_X, logo.height))
    pixels = np.array(art).astype(float)
    rgb, alpha = pixels[..., :3], pixels[..., 3]
    ys, xs = np.mgrid[0 : rgb.shape[0], 0 : rgb.shape[1]]
    alpha = np.where((xs > LOGO_FLASK_EDGE_X) & (ys > LOGO_MOLECULE_BOTTOM_Y), 0, alpha)

    white = np.array([255.0, 255.0, 255.0])

    def coverage(ink):
        d = white - np.array(ink, float)
        cov = np.clip(((white - rgb) @ d) / (d @ d), 0.0, 1.0)
        recon = np.array(ink, float) * cov[..., None] + white * (1 - cov)[..., None]
        return cov, np.abs(recon - rgb).sum(-1)

    cov_navy, err_navy = coverage(INK_NAVY)
    cov_teal, err_teal = coverage(INK_TEAL)
    navy = err_navy <= err_teal

    out = np.zeros_like(pixels)
    out[..., :3] = np.where(navy[..., None], INK_NAVY, INK_TEAL)
    out[..., 3] = np.where(navy, cov_navy, cov_teal) * 255 * (alpha > 0)
    mark = Image.fromarray(out.astype("uint8"), "RGBA")
    return mark.crop(visible_bbox(mark))


def resize_premultiplied(image: Image.Image, size: tuple[int, int]) -> Image.Image:
    """Downscale in premultiplied alpha so transparent pixels cannot bleed white into the edges."""
    pixels = np.array(image.convert("RGBA")).astype(float)
    pixels[..., :3] *= pixels[..., 3:4] / 255.0
    small = np.array(Image.fromarray(pixels.astype("uint8"), "RGBA").resize(size, Image.LANCZOS)).astype(float)
    alpha = np.clip(small[..., 3:4], 1e-6, 255)
    small[..., :3] = np.clip(small[..., :3] * 255.0 / alpha, 0, 255)
    return Image.fromarray(small.astype("uint8"), "RGBA")


def wordmark_from_logo(logo: Image.Image) -> Image.Image:
    """The "Chem+" lettering on its own, edges recovered the same way as the flask."""
    art = logo.convert("RGBA")
    pixels = np.array(art).astype(float)
    rgb, alpha = pixels[..., :3], pixels[..., 3]
    ys, xs = np.mgrid[0 : rgb.shape[0], 0 : rgb.shape[1]]
    # The molecule arm reaches over the lettering, so everything above it is dropped.
    alpha = np.where((xs >= LOGO_WORDMARK_X) & (ys > LOGO_WORDMARK_Y), alpha, 0)
    white = np.array([255.0, 255.0, 255.0])
    d = white - np.array(INK_NAVY, float)
    cov = np.clip(((white - rgb) @ d) / (d @ d), 0.0, 1.0)
    out = np.zeros_like(pixels)
    out[..., :3] = INK_NAVY
    out[..., 3] = cov * 255 * (alpha > 0)
    text = Image.fromarray(out.astype("uint8"), "RGBA")
    return text.crop(visible_bbox(text))


def repaint(art: Image.Image, ink) -> Image.Image:
    """Repaint the navy parts of a mark; the teal liquid and the alpha stay as they are."""
    pixels = np.array(art.convert("RGBA")).astype(float)
    rgb = pixels[..., :3]
    teal = (rgb[..., 1] > rgb[..., 0] + 40) & (rgb[..., 2] > rgb[..., 0] + 40)
    pixels[..., :3] = np.where(teal[..., None], rgb, np.array(ink, float))
    return Image.fromarray(pixels.astype("uint8"), "RGBA")


def feature_graphic(mark: Image.Image, logo: Image.Image) -> Image.Image:
    """1024x500 banner: navy ground, the mark in white on the left, wordmark and claims right.

    Play crops this differently across its surfaces, so nothing that matters comes within
    FEATURE_MARGIN of an edge."""
    w, h = 1024, 500
    ys, xs = np.mgrid[0:h, 0:w]
    blend = ((xs / w) * 0.65 + (ys / h) * 0.35)[..., None]
    ground = np.array(FEATURE_DARK) * (1 - blend) + np.array(FEATURE_LIGHT) * blend
    card = Image.fromarray(ground.astype("uint8"), "RGB").convert("RGBA")

    glow = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    ImageDraw.Draw(glow).ellipse((-40, 60, 480, 560), fill=(*INK_TEAL, 60))
    card.alpha_composite(glow.filter(ImageFilter.GaussianBlur(90)))

    # A loose molecule lattice fills the right side without competing with the text.
    lattice = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    draw = ImageDraw.Draw(lattice)
    rng = np.random.default_rng(7)
    nodes = [(int(a), int(b)) for a, b in rng.uniform([560, 40], [1010, 470], size=(14, 2))]
    for i, (x0, y0) in enumerate(nodes):
        for x1, y1 in nodes[i + 1 :]:
            if (x0 - x1) ** 2 + (y0 - y1) ** 2 < 175**2:
                draw.line((x0, y0, x1, y1), fill=(*FEATURE_TEXT, 26), width=2)
    for x0, y0 in nodes:
        draw.ellipse((x0 - 7, y0 - 7, x0 + 7, y0 + 7), fill=(*INK_TEAL, 70))
    card.alpha_composite(lattice)

    flask = resize_premultiplied(repaint(mark, FEATURE_TEXT), _fit(mark, 300))
    card.alpha_composite(flask, (FEATURE_MARGIN + 46, (h - flask.height) // 2))

    text = repaint(wordmark_from_logo(logo), FEATURE_TEXT)
    text = resize_premultiplied(text, _fit(text, 104))
    left = FEATURE_MARGIN + 46 + flask.width + 64
    card.alpha_composite(text, (left, 150))

    draw = ImageDraw.Draw(card)
    draw.text((left + 4, 288), FEATURE_TAGLINE, font=ImageFont.truetype(FONT_REGULAR, 27), fill=FEATURE_MUTED)
    chip_font = ImageFont.truetype(FONT_SEMIBOLD, 22)
    x = left + 4
    for label in FEATURE_CHIPS:
        width = draw.textlength(label, font=chip_font)
        draw.rounded_rectangle((x, 336, x + width + 40, 382), radius=23, outline=(*INK_TEAL, 190), width=2)
        draw.text((x + 20, 359), label, font=chip_font, fill=FEATURE_MUTED, anchor="lm")
        x = int(x + width + 54)
    return card


def _fit(image: Image.Image, height: int) -> tuple[int, int]:
    return round(image.width * height / image.height), height

def reframe_feature_art(art: Image.Image) -> Image.Image:
    """Fit a hand-supplied banner into Play's 1024x500 without letting type reach the edges.

    Play crops this graphic differently across its surfaces, so the art is scaled to
    FEATURE_ART_SCALE and the ground is replicated outwards to fill the rest - on this cream wash
    that reads as padding rather than a border."""
    art = art.convert("RGB")
    width = round(art.height * 1024 / 500)
    left = (art.width - width) // 2
    framed = art.crop((left, 0, left + width, art.height))
    inner_w = round(1024 * FEATURE_ART_SCALE)
    inner_h = round(500 * FEATURE_ART_SCALE)
    inner = np.array(framed.resize((inner_w, inner_h), Image.LANCZOS))
    pad_x, pad_y = (1024 - inner_w) // 2, (500 - inner_h) // 2
    padded = np.pad(
        inner,
        ((pad_y, 500 - inner_h - pad_y), (pad_x, 1024 - inner_w - pad_x), (0, 0)),
        mode="edge",
    )
    return Image.fromarray(padded, "RGB")

def store_images(favicon: Image.Image, logo: Image.Image, backdrop: Image.Image) -> None:
    # Play Store icon: the mark centred on the icon background, 75% of the canvas tall, so it stays
    # clear of the corners Play rounds off. It comes from the logo rather than the favicon: the
    # favicon's mark is smaller, sits left of centre and would have to be scaled up. Flattened to
    # RGB because Play wants a fully opaque PNG.
    # A hand-supplied mark wins over the logo: store/source/icon-mark.png is the flask drawn at a
    # higher resolution with clean edges (transparent background, the two brand inks).
    mark = (
        Image.open(ICON_MARK_SOURCE).convert("RGBA")
        if ICON_MARK_SOURCE.exists()
        else flask_from_logo(logo)
    )
    mark = mark.crop(visible_bbox(mark))
    height = PLAY_ICON_MARK_PX
    width = round(mark.width * height / mark.height)
    icon = Image.new("RGBA", (512, 512), (*ICON_BACKGROUND, 255))
    icon.alpha_composite(resize_premultiplied(mark, (width, height)), ((512 - width) // 2, (512 - height) // 2))
    write_png(icon.convert("RGB"), STORE / "play-icon-512.png")

    # Feature graphic: the banner at the top of the store listing.
    banner = (
        reframe_feature_art(Image.open(FEATURE_ART_SOURCE))
        if FEATURE_ART_SOURCE.exists()
        else feature_graphic(mark, logo)
    )
    write_png(banner.convert("RGB"), STORE / "feature-graphic-1024x500.png")


# ---------------------------------------------------------------------------------------------
# Vector drawables


def num(value: float) -> str:
    return f"{value:g}"


def to_path_data(tag: str, attrs: dict) -> str:
    if tag == "path":
        return attrs["d"]
    if tag == "line":
        return f"M{num(attrs['x1'])},{num(attrs['y1'])}L{num(attrs['x2'])},{num(attrs['y2'])}"
    if tag == "circle":
        cx, cy, r = attrs["cx"], attrs["cy"], attrs["r"]
        return (
            f"M{num(cx - r)},{num(cy)}"
            f"A{num(r)},{num(r)} 0 1 0 {num(cx + r)},{num(cy)}"
            f"A{num(r)},{num(r)} 0 1 0 {num(cx - r)},{num(cy)}Z"
        )
    if tag == "rect":
        x, y, w, h, r = attrs["x"], attrs["y"], attrs["width"], attrs["height"], attrs.get("rx", 0)
        return (
            f"M{num(x + r)},{num(y)}H{num(x + w - r)}"
            f"A{num(r)},{num(r)} 0 0 1 {num(x + w)},{num(y + r)}V{num(y + h - r)}"
            f"A{num(r)},{num(r)} 0 0 1 {num(x + w - r)},{num(y + h)}H{num(x + r)}"
            f"A{num(r)},{num(r)} 0 0 1 {num(x)},{num(y + h - r)}V{num(y + r)}"
            f"A{num(r)},{num(r)} 0 0 1 {num(x + r)},{num(y)}Z"
        )
    raise ValueError(f"unsupported lucide element: {tag}")


def vector(nodes, color: str, size_dp: int, scale: float, offset: float) -> str:
    paths = "".join(
        f'        <path\n'
        f'            android:pathData="{to_path_data(tag, attrs)}"\n'
        f'            android:strokeWidth="2"\n'
        f'            android:strokeColor="{color}"\n'
        f'            android:strokeLineCap="round"\n'
        f'            android:strokeLineJoin="round" />\n'
        for tag, attrs in nodes
    )
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        + GENERATED_NOTICE
        + '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{size_dp}dp"\n'
        f'    android:height="{size_dp}dp"\n'
        f'    android:viewportWidth="{size_dp}"\n'
        f'    android:viewportHeight="{size_dp}">\n'
        f'    <group\n'
        f'        android:scaleX="{num(scale)}"\n'
        f'        android:scaleY="{num(scale)}"\n'
        f'        android:translateX="{num(offset)}"\n'
        f'        android:translateY="{num(offset)}">\n'
        f"{paths}"
        "    </group>\n"
        "</vector>\n"
    )


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"  {path.relative_to(ROOT)}")


def vector_icons() -> None:
    for key in ("calculators", "virtual_lab", "chemdraw"):
        nodes = LUCIDE[key]
        # 24dp glyph for the pre-Oreo circle icon and a 36dp glyph centered on a 108dp layer.
        write_text(RES / "drawable" / f"ic_shortcut_{key}.xml", vector(nodes, SHORTCUT_GLYPH, 24, 1, 0))
        write_text(
            RES / "drawable" / f"ic_shortcut_{key}_foreground.xml",
            vector(nodes, SHORTCUT_GLYPH, ADAPTIVE_DP, 1.5, 36),
        )
        write_text(
            RES / "drawable" / f"shortcut_{key}.xml",
            '<?xml version="1.0" encoding="utf-8"?>\n'
            + GENERATED_NOTICE
            + '<layer-list xmlns:android="http://schemas.android.com/apk/res/android">\n'
            "    <item>\n"
            '        <shape android:shape="oval">\n'
            '            <solid android:color="@color/icon_background" />\n'
            '            <size android:width="48dp" android:height="48dp" />\n'
            "        </shape>\n"
            "    </item>\n"
            "    <item\n"
            f'        android:drawable="@drawable/ic_shortcut_{key}"\n'
            '        android:width="24dp"\n'
            '        android:height="24dp"\n'
            '        android:gravity="center" />\n'
            "</layer-list>\n",
        )
        write_text(
            RES / "drawable-anydpi-v26" / f"shortcut_{key}.xml",
            '<?xml version="1.0" encoding="utf-8"?>\n'
            + GENERATED_NOTICE
            + '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
            '    <background android:drawable="@color/icon_background" />\n'
            f'    <foreground android:drawable="@drawable/ic_shortcut_{key}_foreground" />\n'
            "</adaptive-icon>\n",
        )
    write_text(RES / "drawable" / "ic_wifi_off.xml", vector(LUCIDE["wifi_off"], OFFLINE_GLYPH, 24, 1, 0))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--web", default="D:/targa/illustrae-clone", help="Chem+ web project root")
    args = parser.parse_args()
    web = Path(args.web)

    favicon = Image.open(web / "public" / "seo" / "favicon.png")
    logo = Image.open(web / "public" / "images" / "logo.png")
    backdrop = Image.open(web / "public" / "chem-bg.webp")

    mark = extract_mark(favicon)
    print("Launcher icons")
    launcher_icons(mark)
    print("Notification icon")
    notification_icon(mark)
    print("Splash")
    splash(logo)
    print("Vector icons")
    vector_icons()
    print("Store images")
    store_images(favicon, logo, backdrop)


if __name__ == "__main__":
    main()
